version: '3.5'
 
services:
  api-cliente:
    image: api-cliente
    build:
      context: .
      dockerfile: Dockerfile

  microservice-empresas:
    image: 957296915963.dkr.ecr.us-east-1.amazonaws.com/microservice-empresas:latest
    depends_on:
      - "mongo"
    environment:
      - "MongoDbConfiguration__ConnectionString=mongodb://danilo_souza:5gHQYNGSGkGXyAx682HezK38X7mzsEaEbTLN@host.docker.internal:27217/admin?ssl=false"

  mongo:
    image: mongo:4.2
    volumes:
      #- "./mongo-fixtures/mongoCliente.js:/docker-entrypoint-initdb.d/mongoCliente.js"
      - "./mongo-fixtures/mongoEmpresas.js:/docker-entrypoint-initdb.d/mongoEmpresas.js"
  
  mongo-express:
    image: mongo-express
    depends_on:
      - "mongo"
  localstack:
        image: localstack/localstack:latest
        container_name: localstack_demo
        ports:
          - '4563-4599:4563-4599'
          - '5003:8080'
        environment:
          - SERVICES=sns
          - DEBUG=1
          - DATA_DIR=/tmp/localstack/data
          - AWS_DEFAULT_REGION=us-east-1
          - AWS_ACCESS_KEY_ID=xxx
          - AWS_SECRET_ACCESS_KEY=xxx
          - HOSTNAME=localhost
          - HOSTNAME_EXTERNAL=localhost
        volumes:
          - './.localstack:/tmp/localstack'
          - '/var/run/docker.sock:/var/run/docker.sock'
          - "./fixtures/aws/aws.sh:/docker-entrypoint-initaws.d/aws.sh"
